name:                hastatus
version:             0.1.0.0
github:              "malyutinegor/hastatus"
license:             MIT
author:              "Egor Malyutin"
maintainer:          "egorcod.tk@gmail.com"
copyright:           "2019 Egor Malyutin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/malyutinegor/hastatus#readme>

dependencies:
- base >= 4.7 && < 5
- X11 >= 1.9 && < 1.10
- utf8-string >= 1.0.1.1 && < 1.0.2.0
- mtl >= 2.2.2 && < 2.3.0
- transformers >= 0.5.5.0 && < 0.5.6.0
- split >= 0.2.3.3 && < 0.2.4.0
- conduit >= 1.3.1 && < 1.4.0

library:
  source-dirs: src

executables:
  hastatus-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hastatus

tests:
  hastatus-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hastatus
